name: Build

on: [push, workflow_dispatch]

jobs:
  build_linux:
    runs-on: ubuntu-22.04
    steps:
    - name: Setup xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build plugin
      run: |
        xmake build -y linux
        xmake build -y swext_linux
    - name: Pack plugin
      run: |
        xmake pack audio_linux
        xmake pack swext_audio_linux
    - name: Upload plugin as artifact
      uses: actions/upload-artifact@v4
      with:
        name: audio_linux
        path: build/xpack/audio_linux/audio_linux.zip
    - name: Upload swiftly extension as artifact
      uses: actions/upload-artifact@v4
      with:
        name: swext_audio_linux
        path: build/xpack/swext_audio_linux/swext_audio_linux.zip
  build_windows:
    runs-on: windows-latest
    steps:
    - name: Setup xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build plugin
      run: | 
        xmake build -y windows
        xmake build -y swext_windows
    - name: Pack plugin
      run: |
        xmake pack audio_windows
        xmake pack swext_audio_windows
    - name: Upload plugin as artifact
      uses: actions/upload-artifact@v4
      with: 
        name: audio_windows
        path: build/xpack/audio_windows/audio_windows.zip
    - name: Upload swiftly extension as artifact
      uses: actions/upload-artifact@v4
      with:
        name: swext_audio_windows
        path: build/xpack/swext_audio_windows/swext_audio_windows.zip

